# Generated by Django 4.0.5 on 2022-11-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudDashboardApp', '0002_alter_document_docfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
