# Generated by Django 4.0.5 on 2022-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datalink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200, null=True)),
                ('nombre', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
